// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615053506_Initial migration seed")]
    partial class Initialmigrationseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.models.Department", b =>
                {
                    b.Property<int>("departmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departmentId"));

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("departmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            departmentId = 1,
                            departmentName = "Production"
                        },
                        new
                        {
                            departmentId = 2,
                            departmentName = "Maintenance"
                        },
                        new
                        {
                            departmentId = 3,
                            departmentName = "Quality Control"
                        });
                });

            modelBuilder.Entity("Domain.models.Role", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roleId"));

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("roleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ShiftMaster.models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("EmployeeID")
                        .IsUnique();

                    b.HasIndex("LocationID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("shiftmaster.models.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<decimal>("ActualHoursWorked")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("AssignmentID")
                        .HasColumnType("int");

                    b.Property<int>("BreakMinutesTaken")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClockIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("VarianceMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AttendanceID");

                    b.HasIndex("AssignmentID")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("shiftmaster.models.AuditLog", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AuditID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("shiftmaster.models.AvailabilitySubmission", b =>
                {
                    b.Property<int>("AvailabilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityID"));

                    b.Property<string>("AvailableDays")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MaxHoursPerWeek")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PreferredShiftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AvailabilityID");

                    b.HasIndex("UserID");

                    b.ToTable("AvailabilitySubmissions");
                });

            modelBuilder.Entity("shiftmaster.models.CoverAssignment", b =>
                {
                    b.Property<int>("CoverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoverID"));

                    b.Property<int>("AssignedByID")
                        .HasColumnType("int");

                    b.Property<string>("CoverType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CoveringUserID")
                        .HasColumnType("int");

                    b.Property<int>("OriginalAssignmentID")
                        .HasColumnType("int");

                    b.Property<bool>("OvertimeApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CoverID");

                    b.HasIndex("AssignedByID");

                    b.HasIndex("CoveringUserID");

                    b.HasIndex("OriginalAssignmentID");

                    b.ToTable("CoverAssignments");
                });

            modelBuilder.Entity("shiftmaster.models.EmployeeSkill", b =>
                {
                    b.Property<int>("EmpSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpSkillID"));

                    b.Property<DateTime>("CertifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("EmpSkillID");

                    b.HasIndex("UserID");

                    b.ToTable("EmployeeSkills");
                });

            modelBuilder.Entity("shiftmaster.models.LabourReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<int?>("GeneratedByID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metrics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReportID");

                    b.HasIndex("GeneratedByID");

                    b.ToTable("LabourReports");
                });

            modelBuilder.Entity("shiftmaster.models.LeaveBlock", b =>
                {
                    b.Property<int>("LeaveBlockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveBlockID"));

                    b.Property<int?>("ApprovedByID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LeaveBlockID");

                    b.HasIndex("ApprovedByID");

                    b.HasIndex("UserID");

                    b.ToTable("LeaveBlocks");
                });

            modelBuilder.Entity("shiftmaster.models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("shiftmaster.models.OvertimeAuthorisation", b =>
                {
                    b.Property<int>("OTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OTID"));

                    b.Property<decimal>("ActualOTHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("AuthorisedByID")
                        .HasColumnType("int");

                    b.Property<string>("OTType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PlannedOTHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OTID");

                    b.HasIndex("AuthorisedByID");

                    b.HasIndex("UserID");

                    b.ToTable("OvertimeAuthorisations");
                });

            modelBuilder.Entity("shiftmaster.models.SchedulingConstraintViolation", b =>
                {
                    b.Property<int>("ViolationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViolationID"));

                    b.Property<int?>("RosterID")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("WeeklyRosterRosterID")
                        .HasColumnType("int");

                    b.HasKey("ViolationID");

                    b.HasIndex("RosterID");

                    b.HasIndex("UserID");

                    b.HasIndex("WeeklyRosterRosterID");

                    b.ToTable("SchedulingConstraintViolations");
                });

            modelBuilder.Entity("shiftmaster.models.ShiftAssignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentID"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RosterID")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftPatternID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("WeeklyRosterRosterID")
                        .HasColumnType("int");

                    b.HasKey("AssignmentID");

                    b.HasIndex("RosterID");

                    b.HasIndex("ShiftPatternID");

                    b.HasIndex("UserID");

                    b.HasIndex("WeeklyRosterRosterID");

                    b.ToTable("ShiftAssignments");
                });

            modelBuilder.Entity("shiftmaster.models.ShiftPattern", b =>
                {
                    b.Property<int>("PatternID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatternID"));

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("DurationHours")
                        .HasColumnType("decimal(4,2)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("MinStaffingLevel")
                        .HasColumnType("int");

                    b.Property<string>("PatternName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PatternID");

                    b.HasIndex("LocationID");

                    b.ToTable("ShiftPatterns");

                    b.HasData(
                        new
                        {
                            PatternID = 1,
                            BreakMinutes = 0,
                            DurationHours = 0m,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            LocationID = 1,
                            MinStaffingLevel = 2,
                            PatternName = "Morning Shift",
                            ShiftType = "Morning",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = "Active"
                        },
                        new
                        {
                            PatternID = 2,
                            BreakMinutes = 0,
                            DurationHours = 0m,
                            EndTime = new TimeSpan(0, 1, 0, 0, 0),
                            LocationID = 1,
                            MinStaffingLevel = 2,
                            PatternName = "Evening Shift",
                            ShiftType = "Afternoon",
                            StartTime = new TimeSpan(0, 17, 0, 0, 0),
                            Status = "Active"
                        },
                        new
                        {
                            PatternID = 3,
                            BreakMinutes = 0,
                            DurationHours = 0m,
                            EndTime = new TimeSpan(0, 9, 0, 0, 0),
                            LocationID = 2,
                            MinStaffingLevel = 1,
                            PatternName = "Night Shift",
                            ShiftType = "Night",
                            StartTime = new TimeSpan(0, 1, 0, 0, 0),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("shiftmaster.models.SkillRequirement", b =>
                {
                    b.Property<int>("SkillReqID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillReqID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("MinCountPerShift")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SkillReqID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("LocationID");

                    b.ToTable("SkillRequirements");
                });

            modelBuilder.Entity("shiftmaster.models.SwapRequest", b =>
                {
                    b.Property<int>("SwapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SwapID"));

                    b.Property<int?>("ApprovedByID")
                        .HasColumnType("int");

                    b.Property<int>("OriginalAssignmentID")
                        .HasColumnType("int");

                    b.Property<int?>("ProposedAssignmentID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequesterUserID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TargetUserID")
                        .HasColumnType("int");

                    b.HasKey("SwapID");

                    b.HasIndex("ApprovedByID");

                    b.HasIndex("OriginalAssignmentID");

                    b.HasIndex("ProposedAssignmentID");

                    b.HasIndex("RequesterUserID");

                    b.HasIndex("TargetUserID");

                    b.ToTable("SwapRequests");
                });

            modelBuilder.Entity("shiftmaster.models.TimesheetSummary", b =>
                {
                    b.Property<int>("TimesheetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimesheetID"));

                    b.Property<int?>("ApprovedByID")
                        .HasColumnType("int");

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PublicHolidayHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RegularHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TimesheetID");

                    b.HasIndex("ApprovedByID");

                    b.HasIndex("UserID");

                    b.ToTable("TimesheetSummaries");
                });

            modelBuilder.Entity("shiftmaster.models.WeeklyRoster", b =>
                {
                    b.Property<int>("RosterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RosterID"));

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RosterID");

                    b.HasIndex("CreatedByID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("LocationID");

                    b.ToTable("WeeklyRosters");
                });

            modelBuilder.Entity("shiftmaster.models.WorkLocation", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.Property<string>("OperatingHours")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocationID");

                    b.HasIndex("ManagerID");

                    b.ToTable("WorkLocations");

                    b.HasData(
                        new
                        {
                            LocationID = 1,
                            City = "Chennai",
                            LocationName = "Chennai Plant",
                            OperatingHours = "09:00-21:00",
                            Status = "Active",
                            Type = "Store"
                        },
                        new
                        {
                            LocationID = 2,
                            City = "Bangalore",
                            LocationName = "Bangalore Hub",
                            OperatingHours = "08:00-20:00",
                            Status = "Active",
                            Type = "Store"
                        });
                });

            modelBuilder.Entity("ShiftMaster.models.User", b =>
                {
                    b.HasOne("Domain.models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("shiftmaster.models.WorkLocation", "HomeLocation")
                        .WithMany("Employees")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("HomeLocation");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("shiftmaster.models.AttendanceRecord", b =>
                {
                    b.HasOne("shiftmaster.models.ShiftAssignment", "Assignment")
                        .WithOne("Attendance")
                        .HasForeignKey("shiftmaster.models.AttendanceRecord", "AssignmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftMaster.models.User", "Employee")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("shiftmaster.models.AuditLog", b =>
                {
                    b.HasOne("ShiftMaster.models.User", "Actor")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("shiftmaster.models.AvailabilitySubmission", b =>
                {
                    b.HasOne("ShiftMaster.models.User", "Employee")
                        .WithMany("Availabilities")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("shiftmaster.models.CoverAssignment", b =>
                {
                    b.HasOne("ShiftMaster.models.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedByID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftMaster.models.User", "CoveringEmployee")
                        .WithMany()
                        .HasForeignKey("CoveringUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("shiftmaster.models.ShiftAssignment", "OriginalAssignment")
                        .WithMany()
                        .HasForeignKey("OriginalAssignmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("CoveringEmployee");

                    b.Navigation("OriginalAssignment");
                });

            modelBuilder.Entity("shiftmaster.models.EmployeeSkill", b =>
                {
                    b.HasOne("ShiftMaster.models.User", "Employee")
                        .WithMany("Skills")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("shiftmaster.models.LabourReport", b =>
                {
                    b.HasOne("ShiftMaster.models.User", "GeneratedBy")
                        .WithMany()
                        .HasForeignKey("GeneratedByID");

                    b.Navigation("GeneratedBy");
                });

            modelBuilder.Entity("shiftmaster.models.LeaveBlock", b =>
                {
                    b.HasOne("ShiftMaster.models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShiftMaster.models.User", "Employee")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("shiftmaster.models.Notification", b =>
                {
                    b.HasOne("ShiftMaster.models.User", "Employee")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("shiftmaster.models.OvertimeAuthorisation", b =>
                {
                    b.HasOne("ShiftMaster.models.User", "AuthorisedBy")
                        .WithMany()
                        .HasForeignKey("AuthorisedByID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftMaster.models.User", "Employee")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorisedBy");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("shiftmaster.models.SchedulingConstraintViolation", b =>
                {
                    b.HasOne("shiftmaster.models.WeeklyRoster", "Roster")
                        .WithMany()
                        .HasForeignKey("RosterID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShiftMaster.models.User", "Employee")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("shiftmaster.models.WeeklyRoster", null)
                        .WithMany("Violations")
                        .HasForeignKey("WeeklyRosterRosterID");

                    b.Navigation("Employee");

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("shiftmaster.models.ShiftAssignment", b =>
                {
                    b.HasOne("shiftmaster.models.WeeklyRoster", "Roster")
                        .WithMany()
                        .HasForeignKey("RosterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("shiftmaster.models.ShiftPattern", "Pattern")
                        .WithMany("Assignments")
                        .HasForeignKey("ShiftPatternID");

                    b.HasOne("ShiftMaster.models.User", "Employee")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("shiftmaster.models.WeeklyRoster", null)
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("WeeklyRosterRosterID");

                    b.Navigation("Employee");

                    b.Navigation("Pattern");

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("shiftmaster.models.ShiftPattern", b =>
                {
                    b.HasOne("shiftmaster.models.WorkLocation", "Location")
                        .WithMany("ShiftPatterns")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("shiftmaster.models.SkillRequirement", b =>
                {
                    b.HasOne("Domain.models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("shiftmaster.models.WorkLocation", "Location")
                        .WithMany("SkillRequirements")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("shiftmaster.models.SwapRequest", b =>
                {
                    b.HasOne("ShiftMaster.models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("shiftmaster.models.ShiftAssignment", "OriginalAssignment")
                        .WithMany()
                        .HasForeignKey("OriginalAssignmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("shiftmaster.models.ShiftAssignment", "ProposedAssignment")
                        .WithMany()
                        .HasForeignKey("ProposedAssignmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShiftMaster.models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftMaster.models.User", "Target")
                        .WithMany()
                        .HasForeignKey("TargetUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("OriginalAssignment");

                    b.Navigation("ProposedAssignment");

                    b.Navigation("Requester");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("shiftmaster.models.TimesheetSummary", b =>
                {
                    b.HasOne("ShiftMaster.models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShiftMaster.models.User", "Employee")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("shiftmaster.models.WeeklyRoster", b =>
                {
                    b.HasOne("ShiftMaster.models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByID");

                    b.HasOne("Domain.models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.HasOne("shiftmaster.models.WorkLocation", "Location")
                        .WithMany("Rosters")
                        .HasForeignKey("LocationID");

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("shiftmaster.models.WorkLocation", b =>
                {
                    b.HasOne("ShiftMaster.models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Domain.models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShiftMaster.models.User", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Notifications");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("shiftmaster.models.ShiftAssignment", b =>
                {
                    b.Navigation("Attendance")
                        .IsRequired();
                });

            modelBuilder.Entity("shiftmaster.models.ShiftPattern", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("shiftmaster.models.WeeklyRoster", b =>
                {
                    b.Navigation("ShiftAssignments");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("shiftmaster.models.WorkLocation", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Rosters");

                    b.Navigation("ShiftPatterns");

                    b.Navigation("SkillRequirements");
                });
#pragma warning restore 612, 618
        }
    }
}
